var texts = [{ "id":1, "data":"19 Enero 2006", "text": "Si me muerdes los labios<br>Que sea con saña,<br>Que me corte la sangre<br>Y me llegue a las entrañas." }, 
             { "id":2, "data": "20 Enero 2006", "text": "Su sonrisa kilométrica<br>Teñía de dientes el horizonte." },
             { "id":3, "data": "13 Abril 2006", "text": "El primer paso<br>Es el más complejo.<br><br>A partir de él<br>Todo inicia<br>Comienza su andadura<br>Fluye<br>Y sirve de engranaje<br>Para lo que se avecina.<br><br>Que sin duda<br>Llenará de arrugas<br>Nuestros pantalones." },
             { "id":4, "data": "15 Abril 2006", "text" : "Atadme de pies y manos<br>Y llevadme a un descampado.<br>Hacedme lo que queráis,<br>Me da igual,<br>Ya estoy salvado."},
             { "id":5, "data": "16 Abril 2006", "text" : "Después de todo lo vivido<br>Ya sólo puedo<br>Soñar<br>Te"},
             { "id":6, "data": "17 Abril 2006", "text" : "El óxido corroe mis entrañas,<br>Llena de moho cada recodo<br>De mi organismo.<br>Es un sabor agudo,<br>Dulce y metálico,<br>Que me recuerda<br>Al crepitar de tus mandíbulas."},
             { "id":7, "data": "18 Abril 2006", "text" : "Ahora sé<br>Que el roce suave<br>Limítrofe<br>Que no llega a cuajar,<br>Es la única razón<br>De la existencia<br>De mis labios."},
             { "id":8, "data": "08 Mayo 2006", "text" : "Y entre<br>Visita y visita<br>Mi vida fluye<br>Mejor que nunca<br>Hacia un futuro incierto<br>Pero lleno de continuos presentes<br>Que le dan sentido<br>A toda vuestra existencia"},
             { "id":9, "data": "18 Mayo 2006", "text" : "Hay días en los que el sol no brilla.<br>Hay días en los que deslumbra.<br><br>Para los días en los que abrase,<br>Taparé mis rasgos,<br>Ocultaré mi piel,<br>Miraré al suelo,<br>Recordaré tus pasos<br>Y bailaré en la oscuridad."},
             { "id":10, "data": "30 Mayo 2006", "text" : "La pureza recorrió sus labios,<br>Con su dulzura empapó las encías,<br>Absorbió toda la superficie y,<br>Por fin,<br>La lengua allanó su morada."},
             { "id":11, "data": "02 Junio 2006", "text" : "Par Impar<br>Izquierda Derecha<br>Así se mezclan<br>Así se unen<br>Se entrecruzan<br><br>Y en ese nudo extremidal,<br>Se fraguan las mejores batallas.<br>En las que se lucha encarnizadamente,<br>Sudando, sangrando y deseando a tu rival,<br>No la peor de las muertes,<br>Sino la mejor de las victorias.<br><br>Par Impar"},
             { "id":12, "data": "05 Junio 2006", "text" : "Perderemos cien batallas<br>Lucharemos bajo cielos estrellados<br>Y veremos caer amigos<br>Y enemigos<br><br>Avanzaremos poco a poco<br>Sufriendo derrotas encarnizadas<br>Ganando guerras de guerrillas<br>Asestando golpes certeros<br>Y recibiendo duras puñaladas<br><br>Será eterno, duro y difícil<br>Pero,<br>No te preocupes.<br>Está escrito,<br>Al final<br>Ganaremos la guerra."},
             { "id":13, "data": "07 Junio 2006", "text" : "Con soles aré la tierra,<br>Con lluvias planté semillas,<br>Tumbado al fresco esperé una buena cosecha,<br>Pero nunca imaginé que fuera tan esplendorosa.<br><br>El sol y la lluvia se fueron<br>Y ahora ya sólo quiero,<br>Perderme en tus<br>Campos de Fresas<br>Para siempre."},
             { "id":14, "data": "03 Julio 2006", "text" : "El sol deslumbraba,<br>No me permitía ver<br>Mi reflejo<br>En el espejo.<br><br>En lugar de eso,<br>Te veía a ti,<br>Sonriéndome,<br>Moviendo las caderas<br>Y haciéndome señas<br>Para que te siguiera.<br><br>Me armé de valor,<br>Salté y lo atravesé.<br><br>Desde entonces,<br>Eres mi guía<br>En la madriguera de conejos<br>De mi país de las maravillas."},
             { "id":15, "data": "17 Agosto 2006", "text" : "Desde esta posición privilegiada<br>Veo tu rayo<br>Balanceándose<br>Y disfruto en demasía<br>De la silueta iluminada<br>Que alumbra mis noches<br>Bajo las sábanas<br>Incombustibles<br>De ardores y quemaduras<br>Interpeneales"},
             { "id":16, "data": "23 Agosto 2006", "text" : "Que mirar hacia atrás<br>Sólo tiene sentido<br>Cuando sabes que vas a encontrar<br>Una marabunta de pelo<br>Y un laberinto de pechos"},
             { "id":17, "data": "16 Septiembre 2006", "text" : "Hubo una vez en que sabía lo que quería.<br>Ahora sólo pienso en franjas de colores.<br>Franjas que van y que vienen,<br>Que con su danzar incesante<br>Me tienen desesperado.<br>Y es esa desesperación<br>La que consigue que me palpiten las encías."},
             { "id":18, "data": "12 Octubre 2006", "text" : "Sales cada noche,<br>Alma pendenciera.<br>Sales cada noche<br>Con la intención de perturbarnos.<br><br>Bebes con desgana,<br>Pero te mantiene viva.<br>Usas el alcohol como aliado.<br>Te mueves digitalmente,<br>Pero te equivocas<br>Todos buscamos chicas analógicas.<br><br>No sudas como siempre,<br>Insuflas a tus poros<br>Un regusto a lujuria<br>Que te sirve de reclamo básico,<br>De pastora de ovejas.<br>Eres carroña de buitres,<br>Cadáver de gusanos,<br>Paredes de ladillas.<br><br>Restriegas tu desgana<br>Contra los muros psicodélicos,<br>Estampas de amor cada esquina,<br>Pero a la vuelta sólo recoges botellas vacías.<br><br>Y las llenas,<br>Con la recolecta de babas que te siguen.<br>Y las llenas,<br>Para tener algo con lo que pasar la noche.<br><br>Pero de vuelta a casa,<br>Nadie te encuentra,<br>Dices que te pierdes<br>Pero sabes de sobra encontrar el camino<br>Al descampado de la vida.<br><br>Ese descampado en el que todos nos rebozamos<br>Acabamos sin ropa,<br>Sedientos de mugre,<br>Inflados de furia,<br>Esperando al sol<br>Que nos reclame.<br><br>Y convertirnos en piedra<br>Del 1 al 69."}, 
             { "id":19, "data": "26 Octubre 2006", "text" : "¿Por qué no te encontré en un mundo mejor?<br>Sin problemas al besarnos,<br>Como ocurre ahora.<br>¿Por qué no te encontré en un mundo mejor<br>Cuando la oscuridad era aún joven,<br>Y crecíamos en la carretera?"}, 
             { "id":20, "data": "03 Diciembre 2006", "text" : "Si me dejaras vivir en tu interior,<br>Serías la primera persona<br>Que albergara pinturas rupestres<br>En las paredes de su útero."},
             { "id":21, "data": "28 Diciembre 2006", "text" : "En un proceso de abstracción<br>Llegué al final de mi mente<br>Dónde la luz es tan oscura<br>Que la oscuridad brilla"},
             { "id":22, "data": "07 Marzo 2007", "text" : "Soy una sombra de mi sombra<br>Y una huella de tus huellas"},
             { "id":23, "data": "21 Mayo 2007", "text" : "He hablado con la locura,<br>La mejor amiga del hombre.<br>He hablado con la locura,<br>Y en un atisbo de amabilidad<br>Me ha incluido en su lista de amantes.<br><br>He hablado con la locura y me ha contado,<br>Que el loco no es loco por ser loco,<br>Es loco porque el resto del mundo no le deja serlo.<br>Loco sin ser loco<br>Cuerdo a duras penas.<br><br>He hablado con la locura cara a cara,<br>Y tenía tu voz."},
             { "id":24, "data": "31 Mayo 2007", "text" : "<i>\'Joven solitaria e incomprendida<br>necesita una parte de cada uno de vosotros,<br>la que más falta os haga,<br>la que más necesitéis,<br>para poder dar a luz una nueva joven<br>solitaria e incomprendida\'</i><br>...<br>Se leía en la sección de contactos.<br><br>Y a las puertas de sus piernas se formó<br>Una cola kilométrica.<br><br>Conocida durante décadas como<br>\'La caravana del amor\'"},
             { "id":25, "data": "15 Junio 2007", "text" : "Y entre la espesura de sus corazones<br>Sólo se oía el chirrido de una cuerda balanceándose<br>Marcando los segundos de un reloj que se había parado"},
             { "id":26, "data": "20 Junio 2007", "text" : "Los corazones sólo bombean sangre.<br>Son los cerebros los que aman."},
             { "id":27, "data": "02 Julio 2007", "text" : "El teléfono móvil al que llama<br>No se encuentra disponible <br>En la actual dimensión espacio/temporal<br>En estos momentos.<br><br>Vuelva a intentarlo de nuevo más tarde."},
             { "id":28, "data": "24 Julio 2007", "text" : "Fuego<br>Que ardan los cielos de caramelo<br>En ríos de muertos garrapiñados<br><br>Que las estrellas fugaces<br>Impacten contra la atmósfera<br>En una lluvia de piedras incandescentes<br><br>Que las rosas contaminen el aire<br>Y los delfines el mar<br><br>Que el caos llame a mi puerta<br>Y bienvenido sea"}, 
             { "id":29, "data": "30 Julio 2007", "text" : "Sobresaltado y sudando<br>Comprendió que no era alrededor del Sol<br>Por dónde orbitaba la Tierra.<br><br>La elipse enredaba su organismo<br>Desde una ceja al tobillo,<br>Siendo su cuerpo<br>El más celeste de todos."}, 
             { "id":30, "data": "12 Agosto 2007", "text" : "Cuando la soledad se apodere de tus entrañas<br>Sintoniza el deglutir de la felicidad <br>A su paso por el píloro."}, 
             { "id":31, "data": "18 Agosto 2007", "text" : "El síndrome de Estocolmo me chupa los talones,<br>Único hueco de carne sin vendar.<br>Mis secuestradores me han abandonado<br>Con una bala en la sien,<br>O a punto de alcanzarla.<br>Se han llevado el dinero<br>Y entre los dólares,<br>Mi alma,<br>Y mi sed vuelve a apaciguarse<br>Por cada centímetro de cerebro que consume la bala."},
             { "id":32, "data": "01 Septiembre 2007", "text" : "Mis ratas echan de menos<br>Morderos los globos oculares<br>Y sorber poco a poco<br>Hasta acabar saciadas,<br>Con 4 dioptrías de más."},
             { "id":33, "data": "19 Septiembre 2007", "text" : "Mi sombra, pobre infeliz<br>Ha decidido dejar de ser mi rastro,<br>Para convertirse en un ente independiente.<br><br>Por eso vivo en penumbra,<br>No quiero sentirme solo<br>Cuando me alumbre el sol."},
             { "id":34, "data": "20 Septiembre 2007", "text" : "Practicando el gerundio<br>Mis sentidos se acentúan<br><br>Mi lengua sabe a rayas blancas<br>En corriente aleatoria circular<br>Alveólica pulmonar<br><br>Y no huelo más que a rata<br>Chamuscada<br>Rata chamuscada bajo la almohada<br><br>Y toco el cielo<br>Y veo el infierno<br><br>Se oyen tambores y clarines<br>Fanfarrias y trompetas<br>Gatillos y fusilamientos<br>Disparos en la boca<br>Aplausos<br><br>Sangrientas las sábanas<br>De oro y malva"},
             { "id":35, "data": "09 Octubre 2007", "text" : "Con la sangre que viertes<br>Disfrazada de sudor<br>Sobre mis costillas,<br>Me haría un collar de coral<br>Que me recuerde el sufrimiento,<br>A cambio de placer,<br>Obtenido a corto plazo.<br><br>La vida sin sangre,<br>No es divertida."},
             { "id":36, "data": "21 Octubre 2007", "text" : "¿Y tú me preguntas si aún te recuerdo?<br>Cómo te voy a olvidar si apareces<br>En todas mis pesadillas."},
             { "id":37, "data": "01 Noviembre 2007", "text" : "Mi día es sólo la antesala de la noche.<br>Sueño para hablar contigo,<br>Hablo contigo en sueños y<br>Cada vez que oigo tu voz<br>Siento que tengo las manos manchadas de sangre."},
             { "id":38, "data": "02 Noviembre 2007", "text" : "Ojalá viviéramos en un mundo de fantasmas,<br>Así, cada noche en vela,<br>Te me aparecerías en carne y hueso."}, 
             { "id":39, "data": "07 Noviembre 2007", "text" : "He visto el globo terráqueo bajo tus pantalones<br>Intenté memorizarlo<br>Pero acabé perdido al sur de Canadá.<br><br>Vamos a engañarnos,<br>Y dime que vives en Ottawa."}, 
             { "id":40, "data": "24 Noviembre 2007", "text" : "Hay días que se pueden resumir en un segundo.<br>Hay segundos que no caben en una lágrima,<br>Lágrimas que inundan el pensamiento de recuerdos,<br>Recuerdos ancestrales de los que está compuesta tu vida,<br>Vida en la que se desmoronan sus pilares básicos<br>Y se mantiene en equilibrio a duras penas.<br><br>Hay días que se pueden resumir en un segundo<br>Segundo que encaja perfectamente con una canción."}, 
             { "id":41, "data": "30 Noviembre 2007", "text" : "Hace cuatro años que sé de ti y<br>Aunque me entiendas a la perfección,<br>Hay conversaciones que prefiero guardar,<br>Así que hoy aquí termino con tu dolor al fin.<br>Volveré para enterrarte más tarde."},
             { "id":42, "data": "03 Diciembre 2007", "text" : "Aprovechando que mi sangre jugueteaba con el alcohol<br>Viéndose incluso hasta superada en número,<br>He viajado al interior de mi alma<br>Desierto sin más paisaje que sol y arena.<br><br>Y en el horizonte, plasmada en un espejismo<br>Has aparecido brillando, brillando y desnuda<br>Como un oasis salvador entre el hambre y la sed.<br>Como un oasis, inexistente."},
             { "id":43, "data": "08 Diciembre 2007", "text" : "Los que conocen nuestra historia,<br>Saben que fuimos al infierno juntos.<br>Me gustó tanto que me agencié una esquina,<br>Donde las cenizas siempre revolotearan alrededor.<br>Tú sin embargo, decidiste ser feliz<br>Y ahora surcas el cielo, a todo color."},
             { "id":44, "data": "12 Diciembre 2007", "text" : "Tras mucho buscar un lugar tranquilo y escondido<br>Donde continuar la fiesta en la intimidad,<br>Llegamos a un after, de paredes rojas y suelos transparentes<br>Cortinas de seda rasgadas y camareras lujuriosas,<br>Que te drogaban con la mirada.<br><br>Desperté dos días más tarde, colmado y satisfecho.<br>No consigo acordarme cómo llegué a aquel lugar de ensueño,<br>Sólo recuerdo que se llamaba Metástasis."},
             { "id":45, "data": "18 Diciembre 2007", "text" : "Si algún día detienes tus pasos,<br>Y te giras porque sientes en tu maltratado ego<br>Que una mirada asesina se posa en tus posaderas,<br>No es que esté adorando tu furtivo caminar.<br>Es que el efecto de las drogas depresivas<br>Mezcladas con sus homólogas excitantes<br>Están rebosando mi alma de felicidad<br>Y mis pupilas,<br>Mis pupilas están orgásmicas."},
             { "id":46, "data": "22 Diciembre 2007", "text" : "Vivo en un mundo monocromo<br>Donde el blanco lucha contra el negro<br>Mientras los grises son meros espectadores<br>De su encarnizada batalla sexual.<br><br>Mi mundo de las ideas, colorido por doquier<br>Se fue al traste súbitamente<br>Cuando me diagnosticaron acromatopsia.<br><br>No hay razón para arrepentirse,<br>Ni echar de menos tanta variedad enfermiza<br>Porque desde siempre me atrajo el blanco,<br>No como el de la claridad,<br>Sino como el del marfil<br>Brillando en el horizonte<br>Cuando agitas la mano al saludar."},
             { "id":47, "data": "30 Diciembre 2007", "text" : "Quise contratar cuatro prostitutas,<br>Una por cada esquina de mi habitación.<br>Adivinaron mis intenciones y me traicionaron.<br>Ahora ellas viven en libertad<br>Pero mis esquinas siguen vacías.<br>Y yo estoy atrapado, como Jack,<br>Sin tripas que destripar."},
             { "id":48, "data": "06 Enero 2008", "text" : "Entraste por la puerta<br>Y saliste por la ventana.<br>Espero que el suelo te reciba como te mereces."}, 
             { "id":49, "data": "9 Enero 2008", "text" : "Si no existieran los espejos,<br>Aún creeríamos en Dios."}, 
             { "id":50, "data": "11 Enero 2008", "text" : "Después de tanto subir<br>Es hora de caer.<br>Este es nuestro último baile,<br>Intentaré no pisarte esta vez."}, 
             { "id":51, "data": "20 Enero 2008", "text" : "Es difícil mantenerse en pie<br>Cuando llevas una orquesta dentro<br>Y cada instrumento se refleja<br>En las lágrimas que poco a poco<br>Pudrirán la madera de mi ataúd."},
             { "id":52, "data": "26 Enero 2008", "text" : "En el sexo nada importa,<br>Ni el cómo, ni el por qué, ni el dónde<br>Ni las alturas desproporcionadas,<br>En horizontal todos somos iguales.<br>Ni siquiera importa el género, ni el número,<br>Lo que realmente marca las pautas<br>Es saber blandir el látigo,<br>Y lamer las botas."},
             { "id":53, "data": "30 Enero 2008", "text" : "A todos nos gusta decir que buscamos ser libres,<br>Pero sed sinceros,<br>Preferís vuestras manos esposadas a la cama."},
             { "id":54, "data": "03 Febrero 2008", "text" : "Tú suenas muy bien, desde siempre.<br>Sólo hay que saber tocarte."},
             { "id":55, "data": "04 Febrero 2008", "text" : "Si la derrota te hace feliz,<br>¿Para qué esperar al enemigo?"},
             { "id":56, "data": "05 Febrero 2008", "text" : "El sexo es la única manera que tenemos de<br>Sentir que no estamos solos en el universo."},
             { "id":57, "data": "08 Febrero 2008", "text" : "De todas las veces que intenté matarte,<br>Ésta no era una de ellas."},
             { "id":58, "data": "09 Febrero 2008", "text" : "¿Por qué me dices la verdad?<br>Si cuando me mientes,<br>Me gustas más."}, 
             { "id":59, "data": "11 Febrero 2008", "text" : "La realidad es una farsa,<br>Y la luz es su infiltrada,<br>Desvelando nuestros defectos en su presencia.<br>No hay más realidad que nuestro interior,<br>Donde abundan las tinieblas personales,<br>Húmeda y bochornosa oscuridad."}, 
             { "id":60, "data": "14 Febrero 2008", "text" : "Tus hijos son los míos.<br>Yo soy el río que fluye en recovecos, <br>Aumentando el caudal de tus paredes vaginales.<br>Yo soy el sol que amamanta tus ansias terrenales, <br>Pecado de los dioses.<br>Yo soy la montaña que penetra en tu desdicha, <br>Causándote la vida.<br>Yo soy la tierra que escupes, <br>Impregnada en óvulo y placenta,<br>Y el aire que contaminas, <br>Con cada uno de tus besos.<br>Y tú eres virgen y deseo, <br>De aquí a la eternidad."}, 
             { "id":61, "data": "17 Febrero 2008", "text" : "En un mundo condenado por la monotonía diaria,<br>La improvisación nos hace libres<br>A sólo aquellos privilegiados con dicha capacidad.<br><br>El resto movéis el mundo,<br>Esclavos de la gravedad."},
             { "id":62, "data": "24 Febrero 2008", "text" : "Podría pasar el resto de mi vida <br>Contando cada uno de tus pelos.<br>Podría arrancártelos en un segundo.<br>O incluso más que eso,<br>Podría peinarte con los dientes<br>Y morderte los pensamientos."},
             { "id":63, "data": "27 Febrero 2008", "text" : "La eternidad es la puerta al cerrarse tras tus pasos, <br>Y tus pasos."},
             { "id":64, "data": "28 Febrero 2008", "text" : "Miedo de mi sombra<br>Siempre persiguiéndome,<br>Como la conciencia,<br>Sangrando."},
             { "id":65, "data": "29 Febrero 2008", "text" : "Cuando se abra la veda<br>Y me apuntes con una escopeta,<br>Asegúrate de apretar el gatillo.<br>Vivo no te hago ningún bien,<br>Pero muerto, te alimento."},
             { "id":66, "data": "02 Marzo 2008", "text" : "Colecciono etiquetas de cerveza,<br>Arrancadas sin piedad, despojadas de su intimidad,<br>En un afán compulsivo, casi catatónico, por<br>Desnudar la botella.<br><br>Colecciono botellas vírgenes,<br>Rezando por ser violadas.<br>Reclamo sexual de estantería,<br>De rojo y polvoriento terciopelo.<br><br>Pero permanecerán así, luciendo palmito,<br>Enjugando con lágrimas sus bajos fondos<br>Durante el resto de los días.<br><br>Siempre fue mejor la tentación,<br>Que morder la manzana."},
             { "id":67, "data": "12 Marzo 2008", "text" : "Me gustaría penetrarte<br>Hasta llegar a las antípodas.<br>Muchos pensarían que disfrutaría,<br>Pero sólo estaría cavando mi propia tumba."},
             { "id":68, "data": "20 Marzo 2008", "text" : "Mi enfermedad es tan simple como compleja:<br>Cada noche me acuesto contigo<br>Y me despierto sin ti.<br><br>Y no es que la fiebre me haga delirar,<br>Siempre encuentro un preservativo a medio usar<br>Tirado a los pies de la cama<br>Testigo de mi incipiente locura,<br>Locura que me ha estado asfixiando durante toda la noche<br>Que me ha tenido erecto y absorto observando sin pestañear<br>Cómo te has ido diluyendo entre mis sábanas."}, 
             { "id":69, "data": "22 Marzo 2008", "text" : "Mis pantalones no me llegan a los tobillos<br>Y no es algo de lo que lamentarse<br>Porque tu falda no te llega a las rodillas<br>Y cada noche doy gracias a dios por ello."}, 
             { "id":70, "data": "27 Marzo 2008", "text" : "Me olvidé por donde sale el sol.<br>De cómo encender un cigarrillo sin fuego,<br>Cómo suena el mar cuando mueres ahogado.<br><br>Me olvidé de llamarte por tu nombre<br>Y ahora todos me suenan a ti.<br><br>Me olvidé de soñar entre sueños<br>De a qué saben las esponjas congeladas y luego incineradas<br>Por qué dejé la puerta abierta <br>Con un ramo de rosas en el recibidor.<br><br>No me acuerdo de nada<br>Pero la nada es placentera.<br><br>Me olvidé de comer y se me cayeron los dientes<br>Y ahora son pedazos de ti<br>Los que tengo incrustados en las encías.<br><br>Me olvidé de la noche y del día<br>Viviendo como alma en pena que lleva el diablo<br>Hacia un fin de sobras conocido y fatal.<br><br>Y las rosas ya se han puesto mustias<br>Aunque, por más que intente recordar,<br>Me olvidé por qué."}, 
             { "id":71, "data": "28 Marzo 2008", "text" : "Un millón de fotos tuyas empapelan mi techo,<br>Para que por fin el hecho de mirar hacia el cielo<br>Cobre algún sentido."},
             { "id":72, "data": "01 Abril 2008", "text" : "Mucho peor que equivocarse<br>Incluso peor que estar siempre equivocado<br>Es permanecer indiferente.<br>De éstos últimos es propiedad el infierno,<br>Dónde pasean orgullosos su inherente pasividad,<br>Su completa falta de afección ante todo.<br> <br>Bienaventurados los que se equivocan,<br>Porque de ellos será el reino de los cielos...<br> <br>Bien, permitid que me arranque las alas,<br>Yo nací para morir achicharrado."},
             { "id":73, "data": "06 Abril 2008", "text" : "Comprendo las 1000 razones por las que me abandonaste,<br>Lo que no entiendo es por qué no te fuiste a la primera."},
             { "id":74, "data": "08 Abril 2008", "text" : "Los corazones sólo bombean sangre.<br>Son los cerebros los que matan."},
             { "id":75, "data": "11 Abril 2008", "text" : "No he vivido mi vida, <br>Mi vida ha vivido por mí,<br>Y espero que al menos haya disfrutado,<br>Porque me ha dejado el cuerpo destrozado."},
             { "id":76, "data": "14 Abril 2008", "text" : "La mueca perfecta no es una sonrisa,<br>Es tu boca retorcida tras asfixiarte,<br>Repetida sin parar en cada rincón de mi cabeza,<br>Como un señuelo a la memoria.<br><br>Y aunque exento de cualquier culpa,<br>La agonía de haberla contemplado<br>No hace más que martillear mis sienes<br>Como el que busca petróleo<br>Y sólo encuentra regueros de masa encefálica.<br><br>Y aunque no te maté<br>No intenté salvarte.<br><br>Más te vale encontrar pronto el infierno<br>Porque mi mente no es el paraíso,<br>Aunque te empeñes por aparecer desnuda en ella,<br>Buscando la manzana que sólo encontrarás<br>Si bajas un poco más.<br><br>Sólo un poco más."},
             { "id":77, "data": "16 Abril 2008", "text" : "Mis sueños no son más<br>Que futuras frases que saldrán de tu boca."},
             { "id":78, "data": "18 Abril 2008", "text" : "Nos encontraremos allí dónde veas salir el sol.<br>No te preocupes si no me ves llegar,<br>Yo soy el sol."}, 
             { "id":79, "data": "27 Abril 2008", "text" : "Lo nuestro es algo imposible,<br>Tú eres animadora del equipo de rugby<br>Y yo he visto StarWars unas 27 veces."}, 
             { "id":80, "data": "30 Abril 2008", "text" : "Quien ideó el primer Metro<br>Debió haberlo inventado sin paradas.<br>El amor a primera vista dura unas tres estaciones,<br>Pero el corazón destrozado pervive durante el resto del viaje."}, 
             { "id":81, "data": "", "text" : ""},
             { "id":82, "data": "", "text" : ""},
             { "id":83, "data": "", "text" : ""},
             { "id":84, "data": "", "text" : ""},
             { "id":85, "data": "", "text" : ""},
             { "id":86, "data": "", "text" : ""},
             { "id":87, "data": "", "text" : ""},
             { "id":88, "data": "", "text" : ""}, 
             { "id":89, "data": "", "text" : ""}, 
             { "id":90, "data": "", "text" : ""}, 
             { "id":91, "data": "", "text" : ""},
             { "id":92, "data": "", "text" : ""},
             { "id":93, "data": "", "text" : ""},
             { "id":94, "data": "", "text" : ""},
             { "id":95, "data": "", "text" : ""},
             { "id":96, "data": "", "text" : ""},
             { "id":97, "data": "", "text" : ""},
             { "id":98, "data": "", "text" : ""}, 
             { "id":99, "data": "", "text" : ""}, 
             { "id":100, "data": "", "text" : ""}, 
             { "id":101, "data":"", "text": "" }, 
             { "id":102, "data": "", "text": "" },
             { "id":103, "data": "", "text": "" },
             { "id":104, "data": "", "text" : ""},
             { "id":105, "data": "", "text" : ""},
             { "id":106, "data": "", "text" : ""},
             { "id":107, "data": "", "text" : ""},
             { "id":108, "data": "", "text" : ""},
             { "id":109, "data": "", "text" : ""},
             { "id":110, "data": "", "text" : ""},
             { "id":111, "data": "", "text" : ""},
             { "id":112, "data": "", "text" : ""},
             { "id":113, "data": "", "text" : ""},
             { "id":114, "data": "", "text" : ""},
             { "id":115, "data": "", "text" : ""},
             { "id":116, "data": "", "text" : ""},
             { "id":117, "data": "", "text" : ""},
             { "id":118, "data": "", "text" : ""}, 
             { "id":119, "data": "", "text" : ""}, 
             { "id":120, "data": "", "text" : ""},
             { "id":121, "data": "", "text" : ""},
             { "id":122, "data": "", "text" : ""},
             { "id":123, "data": "", "text" : ""},
             { "id":124, "data": "", "text" : ""},
             { "id":125, "data": "", "text" : ""},
             { "id":126, "data": "", "text" : ""},
             { "id":127, "data": "", "text" : ""},
             { "id":128, "data": "", "text" : ""}, 
             { "id":129, "data": "", "text" : ""}, 
             { "id":130, "data": "", "text" : ""}, 
             { "id":131, "data": "", "text" : ""},
             { "id":132, "data": "", "text" : ""},
             { "id":133, "data": "", "text" : ""},
             { "id":134, "data": "", "text" : ""},
             { "id":135, "data": "", "text" : ""},
             { "id":136, "data": "", "text" : ""},
             { "id":137, "data": "", "text" : ""},
             { "id":138, "data": "", "text" : ""}, 
             { "id":139, "data": "", "text" : ""}, 
             { "id":140, "data": "", "text" : ""}, 
             { "id":141, "data": "", "text" : ""},
             { "id":142, "data": "", "text" : ""},
             { "id":143, "data": "", "text" : ""},
             { "id":144, "data": "", "text" : ""},
             { "id":145, "data": "", "text" : ""},
             { "id":146, "data": "", "text" : ""},
             { "id":147, "data": "", "text" : ""},
             { "id":148, "data": "", "text" : ""}, 
             { "id":149, "data": "", "text" : ""}, 
             { "id":150, "data": "", "text" : ""}, 
             { "id":151, "data": "", "text" : ""},
             { "id":152, "data": "", "text" : ""},
             { "id":153, "data": "", "text" : ""},
             { "id":154, "data": "", "text" : ""},
             { "id":155, "data": "", "text" : ""},
             { "id":156, "data": "", "text" : ""},
             { "id":157, "data": "", "text" : ""},
             { "id":158, "data": "", "text" : ""}, 
             { "id":159, "data": "", "text" : ""}, 
             { "id":160, "data": "", "text" : ""}, 
             { "id":161, "data": "", "text" : ""},
             { "id":162, "data": "", "text" : ""},
             { "id":163, "data": "", "text" : ""},
             { "id":164, "data": "", "text" : ""},
             { "id":165, "data": "", "text" : ""},
             { "id":166, "data": "", "text" : ""},
             { "id":167, "data": "", "text" : ""},
             { "id":168, "data": "", "text" : ""}, 
             { "id":169, "data": "", "text" : ""}, 
             { "id":170, "data": "", "text" : ""}, 
             { "id":171, "data": "", "text" : ""},
             { "id":172, "data": "", "text" : ""},
             { "id":173, "data": "", "text" : ""}          
            ];